services:
  db:
    image: mysql:latest
    container_name: 'unideal-db-stg'
    ports:
      - '127.0.0.1:23306:3306'
    environment:
      # MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: unideal
      MYSQL_USER: unideal

      # this doesn't matter since this would be only accessible from internal network
      MYSQL_PASSWORD: unideal
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - unideal-db-staging_data:/var/lib/mysql
  app:
    image: ghcr.io/modernweb-team3/backend:887faae
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 10002:8080
    # Refer to this for environment setup:
    # https://docs.spring.io/spring-boot/docs/3.0.4/reference/html/features.html#features.external-config
    environment:
      SPRING_APPLICATION_JSON: ${SPRING_APPLICATION_JSON}

  # Redis
  redis:
    image: redis:7.2.5
    container_name: unideal-redis-stg

volumes:
  unideal-db-staging_data:

# DO NOT REMOVE! - Mitigation for MTU 1400
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

